### ISSUE TITLE
Poison dependency out of date

### ISSUE THREAD

**Issue by haslinger** [manticoresoftware/manticoresearch-elixir#1]
The poison dependency to version 3.0 is out of date, current version is 4.0.1. 
I will try to override locally and report back, if this works out for me.

Thanks for the library!

**Comment by haslinger** [comment]
I realized quickly, it's easier for me to write a thin wrapper around the json interface and have one dependency less in my project, so that issue is not relevant to me any more. Feel free to close this issue at any time.

**Comment by ndrean** [comment]
@haslinger . About the JSON interface: did you evaluate `jsonrs` which claims to be very fast?

**Comment by haslinger** [comment]
@ndrean no nead for speed here, a simple wrapper was enough.

**Comment by ndrean** [comment]
Any guidance on how to do this "wrapper around the json interface"?

**Comment by haslinger** [comment]
@ndrean I'm HTTP-posting to Manticore using HTTPoison and decode the json using Jason as a parser.
I case you want to deep dive into my source, it's open, pushing to Manticore [over here](https://github.com/Panoptikum-social/pan/tree/main/lib/pan/search) and querying data [over there](https://github.com/Panoptikum-social/pan/blob/main/lib/pan/search.ex#L85)
